# combattag.command-whitelist/combattag.command-blacklist
#   White/blacklist of commands which can(not) be executed while tagged
# combattag.tagtime
#   Time in ticks to be tagged.
# combattag.display.mode
#   Output verbosity
#   Possible values:
#     none - Shows no tag messages
#     single - Shows a message if you get tagged
#     per-person - Shows a message if you get tagged by someone who hasn't tagged you yet
#     retag - Shows a message per tag. Very spammy!
world: world
arena:
  region: arena
  spawns: [] # Serialized locations
lobby:
  region: lobby
  spawn: !!null # Serlialized location
combattag:
  command-blacklist:
    - /^/pvp(\b|$)/
  tagback: true
  time: 100 # ticks
  display:
    mode: single
    tag: You got tagged
    untag: You are no longer tagged, you can log out now
