name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${plugin.mainClass}
softdepend: [WorldGuard,Multiverse-Core,Vault]
depend: [Kitter,Spector,ReUtil]
commands:
  pvp:
    permission: pvpmanager.command
  list:
    permission: pvpmanager.command.list
permissions:
  pvpmanager.join.teleport.bypass:
    description: Allows you to bypass automatic teleporting when joining the lobby.
    default: false
  pvpmanager.combattag.bypass:
    description: Allows you to bypass combatlog death.
    default: false
  pvpmanager.admin:
    description: Get PVPManager to treat you different.
    default: op