name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${plugin.mainClass}
softdepend: [WorldGuard,Multiverse-Core]
depend: [Kitter,Spector]
commands:
  pvp:
    permission: pvpmanager.command
permissions:
  pvpmanager.join.teleport.bypass:
    description: Allows you to bypass automatic teleporting when joining the lobby.
    default: false
